config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }, path_names: {sign_in: 'login', sign: 'logout'}

	concern :export_csv do  	
  		get :export_csv, on: :collection 
	end
  
  resources :students  do
		collection do
			get :courses_popup
			get :pie_chart
			get :column_chart
		end
  end

  resources :reports, except: [:show] do
		collection do
			get :requirements
			get :destroy_record
		end
  end
 
   resources :report_generations, concerns: [:export_csv], only:  [:index] do
		collection do
			post :generate_report
			get  :generate_report
		end
  end

  resources :abouts, :apis, only: :index
  resources :feedbacks

  resources :courses, concerns: [:export_csv], except:  [:show] do
		collection do
			get :active_deactive
			get :sorting_list
			get :export_pdf
			get :clear_fliter
			get :populate_courses
		end
  end

  resources :invoices do
	collection do
		get :requirements
		get :show_pending_bills
		get :show_collected_bills
		get :add_collection
		get :invoice_details
		post :save_collection
	end
  end

	#root to: "devise/sessions#new"

	#root :to => redirect("/users/login")
	root :to => "abouts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
	validates :brand_manager, :narration, :invoice_date, :amount, :customer_name, :reference, presence: true

	validates :reference, uniqueness: { case_sensitive: false }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

load_and_authorize_resource

  def index
    @invoices = Invoice.all.paginate :per_page => PER_PAGE, :page => params[:page]
  end

  def show_collected_bills
    invoices = Invoice.joins('JOIN (select abs(sum(collections.amount)) as collection_amount, collections.reference from  collections group by collections.reference ) collections ON invoices.reference = collections.reference').
               where('(invoices.amount - collection_amount) = 0')
    @invoices = invoices.paginate :per_page => PER_PAGE, :page => params[:page]
    render :index
  end

  def show_pending_bills
    invoices = Invoice.joins('LEFT JOIN collections ON invoices.reference=collections.reference').
                where('collections.reference IS NULL')
    @invoices = invoices.paginate :per_page => PER_PAGE, :page => params[:page]
    render :index
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      flash[:notice] =  t('common.created',model_name: Invoice.model_name)
      redirect_to invoices_path
    else
      render :new
    end
  end

  def add_collection    
    @collection = Collection.new(reference: @invoice.reference, collection_date: Date.today)
    render json: {content: render_to_string('invoices/add_collection', locals: {collection: @collection},
          formats: [:html], layout: false ) }
  end

  def save_collection
    @collection = Collection.new(collection_params)
    if @collection.amount.present?
      @collection.amount = -(@collection.amount.abs) 
      collected_total = Collection.where(reference: @collection.reference).sum(:amount).abs 
      invoice_amount = Invoice.where(reference: @collection.reference).first.amount
      @check = ((invoice_amount - collected_total) >= @collection.amount.abs)
      if @check && @collection.save 
        flash[:notice] = 'Collection was successfully added.'
        redirect_to invoices_path
      else
        render :add_collection
      end
    else
      render :add_collection
    end
  end

  def invoice_details
    collections =  Collection.where(reference: @invoice.reference)
    render json: {content: render_to_string('invoices/invoice_details', locals: {invoice: @invoice, collections: collections},
          formats: [:html], layout: false ) }
  end
  
  def update
    if @invoice.update(invoice_params)
      flash[:notice] = t('common.updated',model_name: Invoice.model_name)
      redirect_to invoices_path
    else
      render :edit        
    end
  end

  private
   
   # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:brand_manager, :narration, :invoice_date, :amount, :customer_name, :reference)
    end

    def collection_params
      params.require(:collection).permit(:amount, :collection_date, :reference)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
   def invoices_list_columns
    [
      {label: t('invoice.reference')},
      {label: t('invoice.invoice_date')},
      {label: t('invoice.customer_name')},
      {label: t('invoice.brand_manager')},
      {label: t('invoice.narration')},
      {label: t('invoice.amount')},
      {label: t('invoice.total_collection')},
      {label: t('invoice.balance_due')},
      {label: t('invoice.add_collection')},
    ]
  end

  def total_collection(invoice)
  	Collection.where(reference: invoice.reference).sum(:amount).abs
  end

  def balance_due(invoice)
  	invoice.amount - Collection.where(reference: invoice.reference).sum(:amount).abs
  end

  def is_valid_invoice?
    params[:action] == "show_collected_bills" ? "disabled" : ''  
  end

end

app/views/invoices/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i><b> <%= params[:action].capitalize %> </b>
  </div>
  <div class="panel-body">
    <%= f.input :brand_manager %>    
    <%= f.input :narration %>
    <%= f.input :invoice_date, as: :string, input_html: {class: 'jquery_date'} %>
    <%= f.input :amount %>
    <%= f.input :customer_name %>
    <%= f.input :reference %>
    <%= f.submit submit_btn_text , class: 'btn btn-primary submit-button' %>
  </div>
</div>

app/views/invoices/_invoice.html.erb
<tr>
    <td><%= link_to invoice.reference, 'javascript:void(0);', data: { toggle: "tooltip", title: 'Invoice Details', url: invoice_details_invoices_path(id: invoice.id)}, class: "js_load_modal_popup" %></td>
    <td><%= invoice.invoice_date %></td>
    <td><%= link_to invoice.customer_name, edit_invoice_path(invoice), data: {toggle: "tooltip", title: "edit"} %></td>
    <td><%= invoice.brand_manager %></td>
    <td><%= invoice.narration %></td>
    <td><%= invoice.amount %></td>
    <td><%= total_collection(invoice) %></td>
    <td><%= balance_due(invoice) %></td>
    <td><%= link_to "Add Collection", 'javascript:void(0);', data: {toggle: "tooltip" , title: 'Add Collection amount', url: add_collection_invoices_path(id: invoice.id)}, class: "btn btn-primary js_load_modal_popup #{balance_due(invoice) == 0.0 ? 'disabled' : ''} #{is_valid_invoice?}" %></td>
</tr>

app/views/invoices/_list.html.erb
<div class='table-responsive'>
  <table class="table table-bordered table-hover table-condensed custom-table">
    <thead >
      <%= render 'shared/list_headers', header: 'invoices_list_columns' %>
    </thead>  
    <tbody>
      	<%= render @invoices %>
    </tbody>
  </table>
</div>
<%= render partial: 'shared/pagination', locals: {list_object: @invoices} %>

app/views/invoices/add_collection.html.erb
<div id="add_colloction_error">	
</div>

<%= simple_form_for @collection, url: save_collection_invoices_path , wrapper: :horizontal_form, html: { autocomplete: "off", :class => 'form-horizontal' , :remote => true} do |f| %>
    <%= f.input :reference, input_html: { readonly: true } %>
    <%= f.input :collection_date, as: :string,  input_html: { readonly: true , class: 'jquery_date'} %>
    <%= f.input :amount %>
    <%= f.submit "Add Amount" , class: 'btn btn-primary submit-button-modal' %>
<% end %>

app/views/invoices/add_collection.js.erb
$("#add_colloction_error").html("<%= ['Please enter valid amount'].join('<br>').html_safe %>");

$("#add_colloction_error").addClass("alert alert-danger");

app/views/invoices/edit.html.erb
 <% title = t('common.edit',model_name: Invoice.model_name.human) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, back: true} %>

<%= simple_form_for @invoice, wrapper: :horizontal_form, html: { autocomplete: "off", :class => 'form-horizontal custom-form' } do |f| %>
	<%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/invoices/index.html.erb
<% title = t('common.listing_page',model_name: Invoice.model_name.human.pluralize) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, new: true} %>

<div id="<%= params[:controller]%>_div">
  <%= render 'list' %>
</div>

app/views/invoices/invoice_details.html.erb
<span>
<strong><%= invoice.reference %></strong><br>
<strong><%= invoice.customer_name %></strong><br>
<strong><%= invoice.brand_manager %></strong><br>
<strong><%= invoice.narration %></strong><br><br>

<table class="table table-bordered table-hover table-condensed custom-table">
<thead >
  <th>Date</th>
  <th>Event</th>
  <th>Amount</th>
</thead>  
<tbody>
	<tr>
		<td><%= invoice.invoice_date %></td>
		<td>New /invoice</td>
		<td><%= invoice.amount %></td>
	<tr>
	<%  collections.each do |collection| %>
	<tr>
		<td><%= collection.collection_date %></td>
		<td> Collection</td>
		<td><%= collection.amount.abs %></td>
	</tr>
	<%end%>
	<tr>
	    <td colspan="2" style="text-align: right;">Balance</td>
	    <td><%= balance_due(invoice) %> </td>
	</tr>
</tbody>
</table>
</span>

app/views/invoices/new.html.erb
<% title = t('common.new',model_name: Invoice.model_name.human) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, back: true} %>

<%= simple_form_for @invoice, wrapper: :horizontal_form, html: { autocomplete: "off", :class => 'form-horizontal custom-form' } do |f| %>
	<%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/invoices/requirements.html.erb
<%= render partial: 'shared/display_title_btns', locals: {title: 'Requirements'} %>
<br>
<p>The goal is to build an interface using Rails to view these invoices. 
Two json files will be given. Developer has to load the data from file to database. One file has a list of invoices and the other file has a list of amounts collected against those invoices. Here is an indicative mockup of how the interface should be. </p>
Invoice list</br><br>
<%= image_tag("invoicelist.png", {size: "550x300"}) %>
</br>
</br>
Invoice view </br>
<%= image_tag("invoice-view.png", {size: "500x300"}) %>