config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }, path_names: {sign_in: 'login', sign: 'logout'}

	concern :export_csv do  	
  		get :export_csv, on: :collection 
	end
  
  resources :students  do
		collection do
			get :courses_popup
			get :pie_chart
			get :column_chart
		end
  end

  resources :reports, except: [:show] do
		collection do
			get :requirements
			get :destroy_record
		end
  end
 
   resources :report_generations, concerns: [:export_csv], only:  [:index] do
		collection do
			post :generate_report
			get  :generate_report
		end
  end

  resources :abouts, :apis, only: :index
  resources :feedbacks

  resources :courses, concerns: [:export_csv], except:  [:show] do
		collection do
			get :active_deactive
			get :sorting_list
			get :export_pdf
			get :clear_fliter
			get :populate_courses
		end
  end

  resources :invoices do
	collection do
		get :requirements
		get :show_pending_bills
		get :show_collected_bills
		get :add_collection
		get :invoice_details
		post :save_collection
	end
  end

	#root to: "devise/sessions#new"

	#root :to => redirect("/users/login")
	root :to => "abouts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_display_title_btns.html.erb
<nav class="navbar navbar-expand  custom-nav">
	<div class="container-fluid">
		<ul class="navbar-nav"> 
			<li class="navbar-brand">
				<h2><%= title if defined?(title) %></h2>
			</li>
		</ul>
		<ul class="navbar-nav ml-auto">

			<%  if defined?(new) %>
			<li class="nav-item">
				<%= link_to '<i class="fa fa-file-o" aria-hidden="true"></i> New'.html_safe, {action: 'new', controller: params[:controller]}, :class => "btn btn-primary" %>
			</li>
			&nbsp;
			<%end%>
			<%  if defined?(back) %>
			<li class="nav-item">
				<%= link_to '<i class="fa fa-angle-left" aria-hidden="true"></i> Back'.html_safe, {action: 'index', controller: params[:controller]}, :class => "btn btn-primary" %>		
			</li>
			&nbsp;
			<%end%>
			<%  if defined?(pdf) %>
			<li class="nav-item">
				<%= link_to '<i class="fa fa-file-pdf-o" aria-hidden="true"></i> Export PDF'.html_safe, {action: 'export_pdf', controller: params[:controller]}, :class => "btn btn-primary" %>
			</li>
			&nbsp;
			<%end%>
			<%  if defined?(csv) %>
			<li class="nav-item">
				<%= link_to '<i class="fa fa-file-text-o" aria-hidden="true"></i> Export CSV'.html_safe, {action: 'export_csv', controller: params[:controller]}, :class => "btn btn-primary" %>
			</li>
			<%end%>
		</ul>
	</div>
</nav>			

app/views/shared/_feedback_modal.html.erb
<div id="feedback">
  <%= link_to(image_tag( "feedback", {alt: "Feedback", title: "Feedback Button" ,size: "20x70" }) + "", 
  'javascript:void(0);', data: {title: 'Feedback Form', url: new_feedback_path}, class: 'btn btn-info btn-lg js_load_modal_popup' ) %> 
</div>

app/views/shared/_flash_notice.html.erb
<div class="container">
	<% if flash[:notice].present? %>
		  	<div class="alert alert-success alert-dismissible">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:notice]  %>
			</div>
		  
	<%end%>
	<% if flash[:error].present? %>
		 	<div class="alert alert-danger alert-dismissible">
		    <button type="button" class="close" data-dismiss="alert">&times;</button>
		    	<%= flash[:error]  %>
		    </div>
	<%end%>
	<% if flash[:alert].present? %>
		 	<div class="alert alert-danger alert-dismissible">
		    <button type="button" class="close" data-dismiss="alert">&times;</button>
		    	<%= flash[:alert]  %>
		    </div>
	<%end%>
</div>

app/views/shared/_list_headers.html.erb
<tr>
	<% if defined?(header) and !header.blank? %>  
		<%eval(header).each do |c|%>
			<th><%=c[:label]%></th>
		<%end%>
	<%end%>
</tr>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <span class="navbar-brand" >  
    <i class="fa fa-bars" aria-hidden="true"></i> Menu
  </span>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item  <%= 'active' if current_page?(courses_path)%> ">
      <%= link_to 'Courses', courses_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item  <%= 'active' if current_page?(students_path)%> ">
      <%= link_to 'Students', students_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Chart
      </a>
      <div class="dropdown-menu">
        <%= link_to 'Pie chart', pie_chart_students_path, class: 'dropdown-item' %>
        <%= link_to 'Column chart', column_chart_students_path, class: 'dropdown-item' %>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Invoice Generation
      </a>
      <div class="dropdown-menu">
        <%= link_to 'Requirement', requirements_invoices_path, class: 'dropdown-item'  %>
        <%= link_to 'Invoices', invoices_path, class: 'dropdown-item'  %>
        <%= link_to 'Show Pending Bills', show_pending_bills_invoices_path, class: 'dropdown-item'  %>
        <%= link_to 'Show Collected Bills', show_collected_bills_invoices_path, class: 'dropdown-item'  %>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Sweety
      </a>
      <div class="dropdown-menu">
        <%= link_to 'Requirement', requirements_reports_path, class: 'dropdown-item'  %>
        <%= link_to 'Reports', reports_path, class: 'dropdown-item'  %>
        <%= link_to 'Report Generations', report_generations_path, class: 'dropdown-item' %>
      </div>
    </li>

    <li class="nav-item  <%= 'active' if current_page?(apis_path)%> ">
      <%= link_to 'API', apis_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item  <%= 'active' if current_page?(abouts_path)%> ">
      <%= link_to 'About', abouts_path, class: 'nav-link'  %>
    </li>
  </ul>
   <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <span class="navbar" style="color: white; ">
        Logged in as:&nbsp; <%= current_user.username %></span>&nbsp;
      <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit profile'.html_safe, edit_user_registration_path, class: "btn btn-warning" %>&nbsp;|&nbsp;
      <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Logout'.html_safe, destroy_user_session_path, method: :delete, class: " btn btn-danger" %>
    <% else %>
      <%= link_to '<i class="fa fa-sign-in" aria-hidden="true"></i> Sign up'.html_safe, new_user_registration_path, class: "btn btn-warning" %>&nbsp;|&nbsp;
      <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Login'.html_safe, new_user_session_path, class: " btn btn-warning" %>
    <% end %>
  </ul>
</nav>
<br>

app/views/shared/_modal.html.erb
<div class="modal" id= "load-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_pagination.html.erb
<% if list_object.present? && list_object.size > 0 %>
	<div class="footer-pagination">
		<%= will_paginate list_object %>
	</div>
		<div class="text-center"><%= page_entries_info list_object, entry_name: 'items' %></div>
<% else %>
	<div class="text-center">
	  	<%= t('common.no_records')%>
	</div>
<% end %>

app/views/shared/_spinner_modal.html.erb
<div class="modal hide" id="spinnerModal" data-backdrop="static" data-keyboard="false">
    <div class="spinner-modal-body">
        <div id="ajax_loader">
        	<%= image_tag("loading-gif.gif" ,{alt: "", align: "middle", border: "0", size: "100x100", class: 'spinnner-align' }) %>
        </div>
    </div>
</div>

app/views/shared/_title.html.erb
<div class="jumbotron jumbotron-fluid " style="background-image: url('/assets/green.jpg');background-size: cover;
margin-bottom: 0rem; height: 100%;">
	<div class="container">
	</div>	
</div>

app/views/shared/replace_data.js.erb
$(document).ready(function() {
  $('#<%= @element_id %>').html("<%= escape_javascript(render @partial,  params: @params, filters: @filters ) %>");
});
 
$(document).ready(function() {
  $(".pagination").find("a").attr("data-remote", true);

  $('#j_sort').sortable({
    handle: '.drag',
    cursor: 'move',
    items: 'tr',
    scroll: true,
    update: function(){
      $.ajax({
        url: $('#j_sort').data('url'),
        type: 'get',
        data: $('#j_sort').sortable('serialize'),
        dataType: 'script',
        complete: function(request){
          $('#j_sort').effect('highlight');
        }
      });
    }
  });
});