config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }, path_names: {sign_in: 'login', sign: 'logout'}

	concern :export_csv do  	
  		get :export_csv, on: :collection 
	end
  
  resources :students  do
		collection do
			get :courses_popup
			get :pie_chart
			get :column_chart
		end
  end

  resources :reports, except: [:show] do
		collection do
			get :requirements
			get :destroy_record
		end
  end
 
   resources :report_generations, concerns: [:export_csv], only:  [:index] do
		collection do
			post :generate_report
			get  :generate_report
		end
  end

  resources :abouts, :apis, only: :index
  resources :feedbacks

  resources :courses, concerns: [:export_csv], except:  [:show] do
		collection do
			get :active_deactive
			get :sorting_list
			get :export_pdf
			get :clear_fliter
			get :populate_courses
		end
  end

  resources :invoices do
	collection do
		get :requirements
		get :show_pending_bills
		get :show_collected_bills
		get :add_collection
		get :invoice_details
		post :save_collection
	end
  end

	#root to: "devise/sessions#new"

	#root :to => redirect("/users/login")
	root :to => "abouts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report_generation.rb
class ReportGeneration < ApplicationRecord

 	TYPES=[['Daily', 'daily'], ['Month to date', 'month_to_date'], ['Monthly', 'monthly']]

end

app/controllers/report_generations_controller.rb
class ReportGenerationsController < ApplicationController

	load_and_authorize_resource

	def generate_report
		if ((params.dig(:report, :type).present? && params.dig(:report, :date).present?) || params[:page].present?)
			params[:page].present? ? page_params : report_params
			session[:r_type], session[:r_date]  = params[:report][:type], params[:report][:date] if params.dig(:report, :type).present?
			if session[:r_type] == 'daily'
				reports = Report.includes(:user).where(user_id: helpers.current_user.id).where('reports.created_at::date = :date', date: session[:r_date])
			elsif session[:r_type] == 'month_to_date'
				reports = Report.includes(:user).where(user_id: helpers.current_user.id).where('reports.created_at::date between :from and :to', from: session[:r_date].to_date.beginning_of_month, to: session[:r_date].to_date)
			else
				reports = Report.includes(:user).where(user_id: helpers.current_user.id).where('reports.created_at::date <= :date', date: session[:r_date])
			end
			@report_max_g_level = reports.maximum(:glucose_level)
			@report_min_g_level = reports.minimum(:glucose_level)
			@report_avg_g_level = reports.average(:glucose_level).to_i		
			@result = reports.order('reports.created_at DESC').paginate :per_page => PER_PAGE, :page => params[:page]
			@report_type = session[:r_type]
			session[:report] = reports
			session[:report_type] = [@report_type, @report_max_g_level, @report_min_g_level, @report_avg_g_level, reports.first.try(:user).try(:username)]
			@data = []
			reports.order('reports.created_at DESC').each do |r|
				@data << [r.created_at, r.glucose_level]
			end
			refresh_table
		else
			flash[:error] = t('report_generation.req_fields')
			render :index
		end
	end

	def export_csv
		content = generate_report_list(session[:report], view_context.reports_list_columns.collect{ |r| r[:label] }, session[:report_type])
		filename = "#{session[:report_type][0]}_report.csv"
		send_data  content, :type => 'text/csv', :filename =>  filename, :disposition => 'attachment'
	end

	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
    	params.require(:report).permit(:type,:date)
    end

    def page_params
    	params.permit(:page)
    end

end

app/views/report_generations/_list.html.erb
<br>
<div class='table-responsive'>
  <table class="table table-bordered table-hover table-condensed custom-table">
    <thead >
      <%= render 'shared/list_headers', header: 'reports_list_columns' %>
    </thead>  
    <tbody>
      <%= render partial: 'report_generations/list_item',collection:  list_items, as: :list_item %>
    </tbody>
  </table>
</div>
<%= render partial: 'shared/pagination', locals: {list_object: list_items} %>

app/views/report_generations/_list_item.html.erb
<tr>
    <td><%= list_item.try(:user).try(:username) %></td>
    <td><%= list_item.glucose_level %></td>
    <td><%= list_item.created_at.strftime('%d-%m-%Y') %></td>
</tr>

app/views/report_generations/generate_report.html.erb
<% title = get_title(@report_type)%>

<%= render partial: 'shared/display_title_btns', locals: {title: title, csv: true, back: true} %>

<div style="margin-left: 50px">	
	<li><strong> Maximum Glucose level: <%= @report_max_g_level %></strong> </li> 
	<li><strong> Minimum Glucose level: <%= @report_min_g_level %></strong> </li> 
	<li><strong> Average Glucose level: <%= @report_avg_g_level %></strong> </li> <br>
</div>

<fieldset class="custom_fieldset">
	<%= line_chart @data , xtitle:  'Date', ytitle: 'Glucose level'  %>
</fieldset>

<div id="<%= params[:controller]%>_div">
  <%= render partial: 'report_generations/list', locals: { list_items: @result} %>
</div>

app/views/report_generations/index.html.erb
<% title = "Report Generation" %>

<%= render partial: 'shared/display_title_btns', locals: {title: title} %>

<%= simple_form_for(:report, url: generate_report_report_generations_path,  wrapper: :horizontal_form, html: {autocomplete: "off", class: 'form-horizontal custom-form' }) do |f|%>

<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i><b> Generate </b>
  </div>
  <div class="panel-body">
    <%= f.input :type, label: 'Report Type', collection: ReportGeneration::TYPES %>

    <%= f.input :date, as: :string,  input_html: { readonly: true , class: 'jquery_date'} %>

    <%= f.submit :submit , class: 'btn btn-primary submit-button'%>
  </div>
</div>

<% end %>