config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }, path_names: {sign_in: 'login', sign: 'logout'}

	concern :export_csv do  	
  		get :export_csv, on: :collection 
	end
  
  resources :students  do
		collection do
			get :courses_popup
			get :pie_chart
			get :column_chart
		end
  end

  resources :reports, except: [:show] do
		collection do
			get :requirements
			get :destroy_record
		end
  end
 
   resources :report_generations, concerns: [:export_csv], only:  [:index] do
		collection do
			post :generate_report
			get  :generate_report
		end
  end

  resources :abouts, :apis, only: :index
  resources :feedbacks

  resources :courses, concerns: [:export_csv], except:  [:show] do
		collection do
			get :active_deactive
			get :sorting_list
			get :export_pdf
			get :clear_fliter
			get :populate_courses
		end
  end

  resources :invoices do
	collection do
		get :requirements
		get :show_pending_bills
		get :show_collected_bills
		get :add_collection
		get :invoice_details
		post :save_collection
	end
  end

	#root to: "devise/sessions#new"

	#root :to => redirect("/users/login")
	root :to => "abouts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

load_and_authorize_resource

  before_action :allow_params, only: [:index, :sorting_list]

  def index
    if params[:search].present? 
      conditions = []
      if params[:search][:name].present?
        conditions << "lower(name) LIKE '%#{params[:search][:name].downcase}%'"
        session[:filters_name] = params[:search][:name]
      end
      if params[:search][:description].present?
        conditions << "lower(description) LIKE '%#{params[:search][:description].downcase}%'"    
        session[:filters_desc] = params[:search][:description]
      end
      courses = Course.where(conditions.first).where(conditions.second).order("position")
    else
      courses = Course.order("position")
    end
    session[:filter_type] = params[:filter_type] if params[:filter_type]
    filter_type = session[:filter_type] || 'all'
    courses = dropdown_filter(filter_type, courses)
    session[:courses_list] = courses
    @page_num =  params[:page].present? ? params[:page] : 1
    @courses = courses.paginate :per_page => PER_PAGE, :page => params[:page]
    refresh_table
  end

  def populate_courses
    @courses=  Course.order(:name).where("lower(name) LIKE '%#{params[:term].downcase}%'").map(&:name) 
    render json: @courses
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = t('common.created',model_name: Course.model_name)
      redirect_to courses_path
    else
      render :new 
    end
  end

  def update
    if @course.update(course_params)
      flash[:notice] = t('common.updated',model_name: Course.model_name)
      redirect_to courses_path
    else
      render :edit 
    end
  end


  def active_deactive
    @course.update_attribute('active', (@course.active == 'Y' ? 'N' : 'Y'))
    flash[:notice] = "Modified the status successfully"
    render js: "window.location = '#{courses_path}'"
  end

  def sorting_list
    params[:sorting_ids].each_with_index do |id, index|
      record = Course.where(id: id).first
      record.update_column(:position, ((params[:page].to_i*PER_PAGE-PER_PAGE)+(index+1))) if record.present?
    end
    render js: "window.location = '#{courses_path(page: params[:page])}'"  
  end

  def clear_fliter
    session[:filters_name] = nil
    session[:filters_desc] = nil
    render js: "window.location = '#{courses_path}'"
  end

  def export_csv
    content = generate_course_list(Course.all.order("position"), view_context.courses_list_columns.collect{ |r| r[:label] })
    # Send the file
    filename = "courses_list.csv"
    send_data  content, :type => 'text/csv', :filename =>  filename, :disposition => 'attachment'
  end

  def export_pdf    
    courses = Course.order("position")
    # Create the PDF document
    pdf = Prawn::Document.new
    pdf.move_down 10
    pdf.text "Courses List", size: 13, align: :center, font_style: :bold
    pdf.move_down 10

    data= []
    data << [ 'Name', 'description', 'active','position']

    courses.each {|c|
              data.push([ c.name, c.description, c.active, c.position])
       }
    pdf.table(data, header: true, position: :center, column_widths: [150, 150, 100]) do |table|    
        table.row(0).font_style = :bold
        table.row(0).cell_style = { :text_color => "fafafb"}
        table.row(0).background_color = 'd9d9d9'
    end 

    download_pdf(pdf, "report.pdf")

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :position, :active)
    end

    def download_pdf(pdf, displayed_filename)
      begin
        send_data pdf.render, :filename => displayed_filename
      rescue Exception => ex
        logger.error("Failed to download the pdf file : #{displayed_filename} ! " + ex)
        flash[:error] = 'Failed to download the pdf file !'
        redirect_to :action => 'index'
      end
    end



    def allow_params
      params.permit!
      # params.permit(:filter_type, :page)
      # params.permit(sorting_ids: [])
      # params.permit(search: {})
    end

    def dropdown_filter(filter_type, courses)
      status = case filter_type
      when 'all'        
        return courses
      when 'active'    
        'Y'
      when 'inactive'     
        'N'
      end
      courses.where(active: status).order("position")    
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
   def courses_list_columns
    [
      {label: t('course.name')},
      {label: t('course.description')},
      {label: t('course.active')},
      {label: t('course.position')},
    ]
  end
end

app/views/courses/_active_filter.html.erb
<% path = (defined?(path) and !path.nil?) ? path : '' %>

<div class="dropdown">
  <button type="button" class="btn btn-primary dropdown-toggle pull-right js_dropdown_txt" data-toggle="dropdown">
    Filter
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item js_btn_filter" data-url="<%= path %>" data-value="all" href="javascript:void(0);">All</a>
    <a class="dropdown-item js_btn_filter" data-url="<%= path %>" data-value="active" href="javascript:void(0);">Active</a>
    <a class="dropdown-item js_btn_filter" data-url="<%= path %>" data-value="inactive" href="javascript:void(0);">Inactive</a>
  </div>
</div>

app/views/courses/_course.html.erb
<tr id="sorting_ids_<%=course.id%>">
    <td><%=link_to course.name, edit_course_path(course), {data: {toggle: "tooltip", title: "edit"} } %></td>
    <td><%= course.description %></td>
    <td style="text-align: center"><%= link_to(image_tag( course.active == 'Y' ? "accept" : "reject", 
	{alt: "", align: "middle", border: "0", size: "20x20" }) + "", 'javascript:void(0);', data: {toggle: "tooltip", title: "#{course.active == 'Y' ? 'deactive' : ' active'}", confirmmessage: 'Are you sure, do you want to activate or deactivate?', url: active_deactive_courses_path(id: course.id)}, class: 'bootstrap_confirm' ) %></td>
    <td class="drag" style="text-align: center" ><%= course.position %>
    	 <span data-toggle="tooltip" data-title="drag" >
    		<%=image_tag("arrow", {alt: "", align: "middle", border: "0", size: "20x20" }) %>
    	</span>
    </td>
</tr>

app/views/courses/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i><b> <%= params[:action].capitalize %> </b>
  </div>
  <div class="panel-body">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :active, as: :boolean,
                checked_value: 'Y',
                unchecked_value: 'N',
                length: 10,
                wrapper: :horizontal_radio_and_checkboxes,
                input_html: { checked: @course.new_record? ? true : @course.is_activated?,
                class: 'input-xlarge' },
                required: true %>
    <%= f.submit submit_btn_text , class: 'btn btn-primary submit-button' %>
  </div>
</div>

app/views/courses/_list.html.erb
<div class='table-responsive'>
  <table class="table table-bordered table-hover table-condensed custom-table">
    <thead >
      <%= render 'shared/list_headers', header: 'courses_list_columns' %>
    </thead>  
    <tbody id="j_sort" data-url= "<%= sorting_list_courses_path(page: @page_num) %>">
      <%= render @courses %>
    </tbody>
  </table>
</div>
<%= render partial: 'shared/pagination', locals: {list_object: @courses} %>

app/views/courses/_search_form.html.erb
<%= simple_form_for(:search, url: courses_path, defaults: { required: false } ,html: {autocomplete: "off", id: 'courses_search_form',name: 'courses_search_form', method: :get, class: 'form-horizontal custom-search-form', remote: true }) do |f|%>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= '<i class="fa fa-search" aria-hidden="true"></i> Search'.html_safe %>
  </div>
  <div class='panel-body'>
    <div class="row">
      <div class="col-md-4">
        <%= f.input :name, label: 'Name', input_html:{value: session[:filters_name], data: { source: populate_courses_courses_path} }  %>
      </div>
      <div class="col-md-1" style="float: left; max-width: 15%; margin-top: 1%;">
         OR
      </div>
      <div class="col-md-5">
        <%= f.input :description, label: 'Description', input_html: {value: session[:filters_desc],class: 'desc-field'} %>
      </div>
      <div class="col-md-1 img-responsive">
        <%= link_to "#{image_tag('search.png', {alt: 'Refresh', align: 'middle', border: '0', size: "25x25", local_asset: false})}".html_safe, "javascript:void(0);" ,data: {url: courses_path, form: 'courses_search_form', toggle: "tooltip", title: "search"},class: 'js_custom_refresh'%>
      </div>
      <div class="col-md-1 img-responsive">
        <%= link_to "#{image_tag('clear.png', {alt: 'Refresh', align: 'middle', border: '0', size: "25x25", local_asset: false})}".html_safe, "javascript:void(0);" ,data: {url: clear_fliter_courses_path, form: 'courses_search_form', toggle: "tooltip", title: "clear filter"},class: 'js_custom_refresh'  %>
      </div>
    </div> 
  </div>
</div>
<% end %>

app/views/courses/edit.html.erb
 <% title = t('common.edit',model_name: Course.model_name.human) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, back: true} %>

<%= simple_form_for @course, wrapper: :horizontal_form, html: {autocomplete: "off", :class => 'form-horizontal custom-form' } do |f| %>
	<%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/courses/index.html.erb
<% title = t('common.listing_page',model_name: Course.model_name.human.pluralize) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, new: true, csv: true, pdf: true} %>

<%= render 'search_form' %>

<%= render :partial => 'active_filter', :locals => { :path => "#{courses_path}"} %>

<div id="<%= params[:controller]%>_div" class="js_populate_table_with_filter">
  <%= render 'list' %>
</div>

app/views/courses/new.html.erb
 <% title = t('common.new',model_name: Course.model_name.human) %>

<%= render partial: 'shared/display_title_btns', locals: {title: title, back: true} %>

<%= simple_form_for @course, wrapper: :horizontal_form, html: {autocomplete: "off", :class => 'form-horizontal custom-form' } do |f| %>
	<%= render partial: 'form', locals: {f: f} %>
<% end %>